spring.application.name: task-executor
spring.threads.virtual.enabled: true
spring:
  datasource:
    url: jdbc:h2:mem:task-executor
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        highlight_sql: false

